### ISSUE TITLE
Questions about aspect_ratio and speed

### ISSUE THREAD

**Issue by BestSongEver** [amoussawi/caffe#4]
Hi
Thx for your excellent excellent excellent job!  I'm a new learner and it benefit me a lot.

My question is: i wonder which of these two aspect_ratios configuration work better. How much better ?  and How about the distinction of time cost between them?
-----------------------------------------------------------
(1) in ssd_caltech_512.py
331  aspect_ratio_per_layer = [0.15,0.3,0.41,0.6,0.75,0.9]
332  aspect_ratios = [aspect_ratio_per_layer]*len(mbox_source_layers)
(2) in ssd_caltech_512_ft.py
334  aspect_ratio_per_layer = [0.41]
335  aspect_ratios = [aspect_ratio_per_layer]*len(mbox_source_layers)

Another question is :  i can only run the SSD512 model with the speed about 12 FPS (Geforce GTX Titan X), how can i achieve 24 FPS like u?
------------------------------------------------------------

Thx again again again  :) @amoussawi

**Comment by amoussawi** [comment]
1. [0.41] is slightly better and it's enough to describe the aspect ratio of all pedestrians, apparently the model will eventually adapt because of the location regression. The first one i used it when i was training the model from scratch and i stopped using it so it's not updated. and having less aspect ratios per layer will speed up the model slightly (~2fps).

2. I'm not sure why you are getting 12FPS, if you are running the model on a video, you should get around 20FPS on GTX titan x. the 24 FPS speed is only achieved when you use the caffe time benchmark or when you run the model on the test dataset and average the speed. It's possible that the GPU is not running with high performance, i would say check your nvidia settings.

**Comment by BestSongEver** [comment]
Thanks for your quick and wonderful reply!
It helped a lot.
