### ISSUE TITLE
Error running pre-trained model with original SSD

### ISSUE THREAD

**Issue by LorenaGdL** [amoussawi/caffe#6]
Hi,

First of all, thank you for sharing your code!

I have a question/issue: I'm trying to run the provided pre-trained model with the original SSD code, but I'm getting a couple of errors. First, the field "extra_ar" in the PriorBox layers of the deploy.prototxt cannot be read: `Error parsing text-format caffe.NetParameter: 1010:13: Message type "caffe.PriorBoxParameter" has no field named "extra_ar"`

If such fields are removed, then another error appears: `F0627 07:17:17.537052 12113 detection_output_layer.cpp:164] Check failed: num_priors_ * num_loc_classes_ * 4 == bottom[0]->channels() (163836 vs. 54612) Number of priors must match number of location predictions.`

For what I've seen, your have modified certain things in the SSD architecture, such as the aspect ratio in the layers. However, I though such modifications were self-contained, i.e. they only affected definitions and scripts, but that the resulting deploy.prototxt and .caffemodel were compatible with mainstream SSD. Is that the case, or is your branch needed to run the model for inference? Any tips or explanations about the error are welcomed!

Thanks!

**Comment by amoussawi** [comment]
Hi. `extra_ar` is not part of the original code, maybe i should have done a pull request. Anyway, the original SSD uses two default bouding boxes with same aspect ratio of 1 but different scales. For pedestrian detection, we don't need 1.0 aspect ratio since 0.41 was enough to describe the distribution of the pedestrians, so we had to do this additional modification of making these additional default bbox as optional. 
The second error you are getting is because as if `extra_ar` is set to true even though it's not used in the original code. The original code will automatically add the two additional bboxes which won't match with the provided caffemodel file.

**Comment by LorenaGdL** [comment]
Understood. Thank you :)
