### ISSUE TITLE
Estimating the number training iterations

### ISSUE THREAD

**Issue by a64bit** [amoussawi/caffe#7]
Hi Abdallah, 
Thank you for the great work and sharing your code. 

 I have few questions about training settings. How did you know that after 20K iterations the model starts to overfit ? and how many training images did you have, and the number of epochs this 20K represents ? 

Thank you.

**Comment by amoussawi** [comment]
1. I evaluated with mAP that is already computed in the SSD evaluation code. I noticed that getting higher mAP results in lower miss-rate, that's how i validated, also i was evaluating the model with the caltech evaluation every few iterations (5k i remember) and beyond 20k the miss rate was going higher instead of lower. Also note that I'm fine-tuning and not training from scratch, which is why you don't need much iterations. 

2. since we have a batch size of 32 (in my script) and 20k iterations, that means 32*20k samples, and since i'm taking a frame every 5 frames, we have 26k images, which is around 25 epochs.
